<?php
return[
    [
        'product_name'=>'Intestines',
        'product_type'=>'meat_product',
        'uom'=>'kg'
    ],
    [
        'product_name'=>'Liver',
        'product_type'=>'meat_product',
        'uom'=>'unit'
    ],
    [
        'product_name'=>'Kidney',
        'product_type'=>'meat_product',
        'uom'=>'unit'
    ],
    [
        'product_name'=>'Skin',
        'product_type'=>'meat_product',
        'uom'=>'kg'
    ],
    [
        'product_name'=>'Horns',
        'product_type'=>'meat_product',
        'uom'=>'unit'
    ],
    [
        'product_name'=>'Hooves',
        'product_type'=>'meat_product',
        'uom'=>'Unit'
    ],
    [
        'product_name'=>'Red meat',
        'product_type'=>'meat_product',
        'uom'=>'kg'
    ],
    [
        'product_name'=>'Head',
        'product_type'=>'meat_product',
        'uom'=>'unit'
    ],
    [
        'product_name'=>'African Sausage',
        'product_type'=>'meat_product',
        'uom'=>'kg'
    ],
    [
        'product_name'=>'Cow',
        'product_type'=>'Livestock',
        'uom'=>'unit'
    ],
    [
        'product_name'=>'Pig',
        'product_type'=>'Livestock',
        'uom'=>'unit'
    ],
    [
        'product_name'=>'Goat',
        'product_type'=>'Livestock',
        'uom'=>'unit'
    ],
    [
        'product_name'=>'Chicken',
        'product_type'=>'Livestock',
        'uom'=>'unit'
    ],
];
